INSERT INTO code_list(code,name,loc) VALUES ('333','Emily','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('3331','Nate','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('3332','Tiffany','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('444','Jackson','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('444222','Ann','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('444444','Harris','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('444555','Will','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('666','Jack Hu','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('777','Sheldon','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('777111','Leo Liang','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('777222','Bambi','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('111111','Jason','Syd');
INSERT INTO code_list(code,name,loc) VALUES ('333333','Sam','Syd');
INSERT INTO code_list(code,name,loc) VALUES ('555555','Elva','Syd');
INSERT INTO code_list(code,name,loc) VALUES ('888888','Leo','Syd');
INSERT INTO code_list(code,name,loc) VALUES ('0','Flynn','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('111','William','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('222','Zoe','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('555','Sherry','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('888','Mia','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('8888','Michael','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('999','Joy','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('222222','Kimmy','Syd');
INSERT INTO code_list(code,name,loc) VALUES ('555111','Zane','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('9991','Leah','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('3334','Ethan','Mel');
INSERT INTO code_list(code,name,loc) VALUES ('3335','Eric','Mel');
